CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  number TEXT NOT NULL UNIQUE,
  pin TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);
